### ISSUE TITLE
SerialPort.write returns 0 bytes written

### ISSUE THREAD

**Issue by markprocess** [euantorano/serial.nim#11]
I am trying to write to the uart that is connected to the hci/uart interface of a bluetooth chip on board a raspbian/pi3b+. When I run this program, it indicates that 0 of 3 bytes have been written.

1. do you recognize this problem?

2. how can I determine why 0 bytes were written instead of 3?

Thanks,
Mark

```
import serial, strformat

when isMainModule:
  proc main() =

    echo ""
    var portName = "/dev/ttyAMA0"

    let serialPort = newSerialPort(portName)
    serialPort.open(38400, Parity.None, 8, StopBits.One)
    defer: close(serialPort)

    echo &"Opened serial port {portName}"

    var nop = newString(3)
    var n = serialPort.write(nop)
    echo &"{n}/{len(nop)} bytes written"

  main()

```

**Comment by euantorano** [comment]
That's odd, I'm not sure what would cause this. I've only tested with the hardware that I have available to me:

- Physical serial port on Linux and Windows desktop machines
- USB to serial adapters (RS232 and RS485) using a chip from FTDI: http://www.ftdichip.com/Products/Cables/USBRS232.htm
- B&B Electronics serial to IP adapter using virtual COM port on Windows
- Moxa NPort serial to IP adapters (5110 RS232 and 5130 RS485) using virtual COM port on Windows

If you try the write again (eg: try writing in a loop) does it ever return a value other than `0`? The 0 value is probably being returned by [`posix.write`](https://github.com/euantorano/serial.nim/blob/master/src/serial/private/serialport/serialport_posix.nim#L691), which you could confirm by adding an `echo` after that line to ensure it got that far (it can also return 0 [if the buffer is nil or the length is 0](https://github.com/euantorano/serial.nim/blob/master/src/serial/serialport.nim#L47), neither of which are true in this case).

**Comment by markprocess** [comment]
Thank you for your help. I discovered that
```
    hciattach -r /dev/ttyAMA0 bcm43xx 38400 noflow
```
was interfering with my use of the uart. I won't pursue why this causes the 0 bytes written return value.
