### ISSUE TITLE
IOKit/IOKitLib.h not found under macOS 10.14 (Mojave)

### ISSUE THREAD

**Issue by brakmic** [euantorano/serial.nim#13]
Hi,

I am getting the error message that `IOKit/IOKitLib.h` could not be found. 

The code I try to compile is: 
```nim
import serial 

for port in listSerialPorts():
  echo port
```

First I've tried it with `--cincludes:/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers` as it contains the subdirectory `IOKit`.

However, after a few attempts I realized that IOKitLib.h is not there but instead inside `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers`. 

What's missing is the subdirectory `IOKit` that contains `IOKitLib.h`.

Is this problem only related to **macOS Mojave** or am I maybe missing some SDK settings?

Kind regards,

**Comment by euantorano** [comment]
I haven’t tested on Mojave yet, but I assume you have XCode and the XCode command line tools installed? I think they might be required, which I should document if so.

**Comment by brakmic** [comment]
Yes, I have the latest XCode 10.0 and I also have installed the command line tools with `xcode-select --install`.

**Comment by euantorano** [comment]
I'll have to give this a go this weekend. I haven't updated my Mac to Mojave just yet, so I need to do that first and see if I can figure out the problem. The code doesn't hard code the path to the library ([see here](https://github.com/euantorano/serial.nim/blob/master/src/serial/private/utils/list_serialports_mac.nim#L3)) so I think this is something at the compiler/linker level.
