### ISSUE TITLE
Compile errors on macOS Mojave

### ISSUE THREAD

**Issue by euantorano** [euantorano/serial.nim#17]
Examples and this library are currently failing to compile on macOS Mojave, see the following Nimbuses issue related to `posix/termios`: https://github.com/nim-lang/Nim/issues/10002

**Comment by mp035** [comment]
See #18 .  I may have inadvertently broken OSX compatibility with my patch for linux.  Please double check the patch contents for #18 .  I have re-implemented the old constants which were only for OSX.   That should fix this issue, but I do not have a current model Mac to test on.

**Comment by euantorano** [comment]
Great, thanks @mp035. I'll check it out. I still think it's an issue for Nim to have variables defined in the standard library that don't work, so I'll keep the issue open over there.

**Comment by mp035** [comment]
I agree.  The termios implementation on linux does not include baud rates above 38400 for linux either, so it seems they are using some minimal version of termios.h for their posix implementation.
