### ISSUE TITLE
Asynchronous IO blocks dispatcher thread.

### ISSUE THREAD

**Issue by mp035** [euantorano/serial.nim#18]
The async read and write operations perform an instant call to posix.read or posix.write before adding a read or write to the dispatcher queue.  This causes the dispatcher thread to block under certain circumstances (no data available), preventing completion of other operations in the dispatcher queue.

A patch is attached which corrects the issue, it was tested on Ubuntu 18.04.  

**NOTE: it also re-implements the OSX baudrate constants which were removed in my last patch and should fix issue #17 .**

Sorry for the regression.

[fix_async_block.zip](https://github.com/euantorano/serial.nim/files/2683245/fix_async_block.zip)

**Comment by euantorano** [comment]
Unfortunately it looks like the attached patch doesn't want to apply, but I've implemented the change manually anyway:

```
error: patch failed: src/serial/private/serialport/serialport_posix.nim:682
error: src/serial/private/serialport/serialport_posix.nim: patch does not apply
```

I've now tagged v1.1.2 which includes this fix and fixes the compile errors on Mac. Thanks!

**Comment by mp035** [comment]
I'm sorry to say that the hand application of the patch didn't go as planned.   The source looks different to mine.  It no longer compiles on Ubuntu 18.10 and the serial port constants look wrong for OSX.  I've forked it and I'l fix it and send a pull request for you to look at.
