### ISSUE TITLE
How can I write data to serial while reading data from it

### ISSUE THREAD

**Issue by loongw** [euantorano/serial.nim#2]
I am rolling a simple serial term which has simple functions:

- Reading text from serial port and print it to stdout.
- Reading user's input from stdin and write it to serial port.

How can I get both work together?
My experience from other language is to use multithread or async IO.
Multithread seems not a way due to Nim's per-thread gc. Also serial.nim does not support asyncio yet.
What's the best solution for now?

**Comment by euantorano** [comment]
You could do it multithreaded by making the serial port instance a shared object (or by passing a pinter to it to your read/write thread). I haven't written any code to do this myself before, but it should be possible. I can try it this weekend and provide an example if I get it working.

Async IO would be the best approach obviously, but I haven't yet implemented that in this library.

**Comment by loongw** [comment]
Sounds workable. I'll have a try. Thanks.

**Comment by loongw** [comment]
The multithreaded way is so tedious in Nim.
Eventually,  I chose the async way, with some modification of serial.nim:
- Add async flag for the open, and add a getFileHandle for SerialPort.
```nim
proc test() {.async.} =
  let port = newSerialPort("COM1")
  port.open(57600, Parity.None, 8, StopBits.One, async=true)
  let com = port.getFileHandle().AsyncFd.newAsyncFile()
  while true:
    echo await com.readLine()

waitFor test()
```
This way seems simpler and more flexible.

**Comment by euantorano** [comment]
Nice. Did you test this on Windows at all or just on Linux?

**Comment by loongw** [comment]
My app is for Windows, so I tested only on Windows XP so far.

**Comment by r3d9u11** [comment]
@loongw @euantorano Hi!
I tried this code, but compilation failed :(
 Is there any news about this issue?

**Comment by euantorano** [comment]
Hi, sorry I’ve been really busy. I still mean to implement an AsyncSerialPort. I’ll try find some time to do it during June.

**Comment by euantorano** [comment]
Async support is here now, in #9 @r3d9u11. I haven't yet tested this on Linux or Mac at all, but have tested on Windows 10 and it's functioning well. Once I test on Mac and Linux later on today I will merge it and tag a new release.
