### ISSUE TITLE
Read timeout does not function correctly on windows implementation.

### ISSUE THREAD

**Issue by mp035** [euantorano/serial.nim#27]
Hi, when using read timeouts other than 0 or TIMEOUT_INFINITE, the windows implementation behaves as outlined in the following remark from  [https://docs.microsoft.com/en-gb/windows/win32/api/winbase/ns-winbase-commtimeouts](https://docs.microsoft.com/en-gb/windows/win32/api/winbase/ns-winbase-commtimeouts):

> 
> - If there are any bytes in the input buffer, ReadFile returns immediately with the bytes in the buffer.
> - If there are no bytes in the input buffer, ReadFile waits until a byte arrives and then returns immediately.
> - If no bytes arrive within the time specified by ReadTotalTimeoutConstant, ReadFile times out.
> 

I believe this is not the intended behaviour.  With a single timeout, I would anticipate that the port reading process would simply timeout if the requested number of bytes is not received within the set timeout period (please correct me if I am wrong).

I have applied a fix which produces the expected behaviour for read timeouts other than zero and infinite (tested) to my fork.  It also seems that the settings for TIMEOUT_INFINITE were not according to the specification, so I have corrected those, and have tested that the port does not timeout for about 10 minutes (this should be sufficient to confirm correct behaviour, testing for infinite is impossible).  The commit is here: 
[https://github.com/mp035/serial.nim/commit/836d53fd385575238382c2feb7f5db94d0b7828b](https://github.com/mp035/serial.nim/commit/836d53fd385575238382c2feb7f5db94d0b7828b)

I'm happy to issue a pull request, but please note my comments on 2 of the other issues before accepting my offer.

**Comment by euantorano** [comment]
I can’t remember if I’ve ever properly tested the timeouts yet as the applications I’m normally writing tend to not care about timeouts, so thanks for testing this. A PR would be appreciated for sure.

**Comment by euantorano** [comment]
Fixed in #29
