### ISSUE TITLE
Setting write timeout to zero results in TIMEOUT_INFINITE on windows.

### ISSUE THREAD

**Issue by mp035** [euantorano/serial.nim#28]
Sorry for all the issues today, I have been giving the windows version a workout in my new project.

If write timeout is set to zero, the windows version applies TIMEOUT_INFINITE.  Setting write timeout to zero is not actually possible in windows, so I have applied a fix which applies a 1ms timeout in the case of the user requesting zero.  It's not perfect, but its better than applying infinite timeout.

The fix is here:
[https://github.com/mp035/serial.nim/commit/0db8e05c07503dfdb1e3f5ebb9d56de84088e62e](https://github.com/mp035/serial.nim/commit/0db8e05c07503dfdb1e3f5ebb9d56de84088e62e)

As with the other issues, let me know if you want me to file a pull request.
Thanks again for all your work on this project.

**Comment by euantorano** [comment]
Not a problem! I’m just happy people are using the library :)

As with the other issues, a PR is appreciated. Only change I’d suggest is to add a comment to the function to make the behaviour clear.

**Comment by euantorano** [comment]
Fixed in #29
