### ISSUE TITLE
ffi_windows.nim(29, 27) Error: cannot convert 4294967295 to DWORD

### ISSUE THREAD

**Issue by essess** [euantorano/serial.nim#31]
Using NIM 1.0.0 on Windows10. Did a `nimble install serial` this morning.

I'm new to NIM and simply tried the following snippet from your examples to see what happens:
```
import serial # Or: `import serial/utils`

for port in listSerialPorts():
  echo port
```
I get the error in the title.
I did some searching and found out that DWORD is an int32, but the referenced line in the error attempts to use uint32. So I ran a quick sanity check:
```
echo high(int32)    => 2147483647
echo high(uint32)   => 4294967295
```
I'm pretty sure I understand what's going on here (impressed by it, actually), but I don't have any idea how to fix it for you.

**Comment by euantorano** [comment]
Can you try using `nimble install serial@#head` and see if that fixes the problem? There have been a few fixes recently and I haven't tagged a new release yet as I want to make some more changes first.

**Comment by essess** [comment]
Works. I'll run with this and keep the `@#head` trick in mind for my other adventures. Thanks!

**Comment by euantorano** [comment]
No problem. I’ll tag a new version once we get the serial port listing changes made.
