### ISSUE TITLE
Error: type mismatch: got  <clong> but expected 'Suseconds = int32'

### ISSUE THREAD

**Issue by Imperator26** [euantorano/serial.nim#36]
Tried to run
```
import serial

for port in listSerialPorts():
  echo port
```

but I get `/.nimble/pkgs/serial-1.1.2/serial/private/serialport/serialport_posix.nim(633, 26) Error: type mismatch: got
 <clong> but expected 'Suseconds = int32'`

**Comment by euantorano** [comment]
What platform is this on? Can you try master rather than 1.1.2? I need to tag a new version.

**Comment by Imperator26** [comment]
I'm on macOS Catalina 10.15.2

**Comment by euantorano** [comment]
I’m on the same platform, last time I tried HEAD it worked so I’d definitely recommend trying that until I tag a new release. I’m away from the computer right now but will tag one later today.

**Comment by Imperator26** [comment]
Alright np

**Comment by Imperator26** [comment]
Master works fine!
