### ISSUE TITLE
Need support baud rate greater than 38400 on posix systems.

### ISSUE THREAD

**Issue by loongw** [euantorano/serial.nim#4]
pyserial does this:
https://github.com/pyserial/pyserial/blob/master/serial/serialposix.py

**Comment by loongw** [comment]
pyserial does this:
https://github.com/pyserial/pyserial/blob/master/serial/serialposix.py

**Comment by euantorano** [comment]
I'll see what I can do. The thing that I'm trying to avoid is for end users having to do stuff like:

```nim
when defined(linux):
  port.baudRate = 38400
else:
  port.baudRate = 9600
```

**Comment by euantorano** [comment]
Awesome, I’d be happy to see a posix only patch for now, I can look at the Windows side at a later point.
