### ISSUE TITLE
undeclared identifier: 'PCustomOverlapped'

### ISSUE THREAD

**Issue by TensorTom** [euantorano/serial.nim#44]
nim: 1.2.6 win32

code:
```
import serial

for port in listSerialPorts():
    echo port
```
error:
```
.nimble\pkgs\serial-1.1.4\serial\private\serialport\serialport_windows.nim(637, 12) Error: undeclared identifier: 'PCustomOverlapped'
```

**Comment by euantorano** [comment]
Looks like there must have been a change in Nim. The `PCustomOverlapped` type used to be declared in `asyncdispatch` but there’s no reference to it now and I can’t find it using GitHub search either...

**Comment by euantorano** [comment]
Just found the commit: https://github.com/nim-lang/Nim/commit/76269074014b672582bc630ff393a95e5e21dcec#diff-e7d29941cb2ca6bf4e0f5c627239bc7b

Are you using Nim `devel`?

Looks like I will need to re-think the asynchronous support...

**Comment by leeooox** [comment]
I found similar issue  with nim-1.2.6_x64 on windows10 64bit.

1. these code works:
import serial/utils
for port in listSerialPorts():
  echo port

2. these code report errors:
import serial/utils, serial/serialport
for port in listSerialPorts():
  echo port

let port = SerialPort("COM5")

.nimble\pkgs\serial-1.1.4\serial\private\serialport\serialport_windows.nim(637, 12) Error: undeclared identifier: 'PCustomOverlapped'

**Comment by euantorano** [comment]
Ok, looks like I’ll need to add some conditional compilation or something to fix it, will look into it today.

**Comment by euantorano** [comment]
@leeooox Any chance you could give #45 a try? I don't currently have access to a Windows machine to test with.

**Comment by euantorano** [comment]
Never mind, I found a Windows machine and gave it a go - seems to fix the problem 😄

**Comment by leeooox** [comment]
@euantorano Thanks for fixing the  issue, I double check it works on my win10 64bit PC with Nim 1.2.6
